schema_version = "1.0.0"

id = "clone_fields"
version = "0.1.59"
name = "Clone Fields"
tagline = "Procedural clone fields for modeling"
maintainer = "Bryan Leister"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:MIT"]
