"""Shared names for Clone Fields data and node group sockets."""

ADDON_NAME = "Clone Fields"

CLONER_OBJECT_NAME = "Cloner"
CLONER_MESH_NAME = "Clone Fields Output"
CLONER_MODIFIER_NAME = "Cloner"
GRID_NODE_GROUP_NAME = ".Clone Fields Grid Cloner"

PROP_CLONER_TYPE = "clone_fields_type"
PROP_CLONER_MODE = "clone_fields_mode"
PROP_CLONER_ID = "clone_fields_id"
PROP_MANAGED_SOURCE = "clone_fields_managed_source"
PROP_SOURCE_OWNER = "clone_fields_source_owner"
PROP_SOURCE_COLLECTION = "clone_fields_source_collection"
PROP_SOURCE_COLLECTION_OWNER_ID = "clone_fields_source_collection_owner_id"
PROP_EFFECTOR_TYPE = "clone_fields_effector_type"
PROP_EFFECTOR_SHAPE = "clone_fields_effector_shape"
PROP_SPACING_MODE_PREVIOUS = "clone_fields_spacing_mode_previous"
PROP_NODE_GROUP_BUILD_VERSION = "clone_fields_node_group_build_version"
GRID_NODE_GROUP_BUILD_VERSION = 14
EFFECTOR_STRENGTH_PERCENT_DEFAULT = 100

SOCKET_GEOMETRY = "Geometry"
SOCKET_SOURCE_OBJECT = "Source Object"
SOCKET_SOURCE_COLLECTION = "Source Collection"
SOCKET_SOURCE_COUNT = "Source Count"
SOCKET_EFFECTOR_OBJECT = "Plain Effector"
SOCKET_EFFECTOR_TYPE = "Effector Type"
SOCKET_EFFECTOR_FIELD = "Effector Field"
SOCKET_EFFECTOR_SEED = "Effector Seed"
SOCKET_EFFECTOR_ENABLED = "Effector Enabled"
SOCKET_EFFECTOR_INVERT = "Effector Inverse"
SOCKET_EFFECTOR_STRENGTH = "Effector Strength"
SOCKET_EFFECTOR_RADIUS = "Effector Radius"
SOCKET_EFFECTOR_HEIGHT = "Effector Height"
SOCKET_EFFECTOR_LENGTH = "Effector Length"
SOCKET_EFFECTOR_FALLOFF = "Effector Falloff"
SOCKET_EFFECTOR_USE_POSITION = "Effector Use Position"
SOCKET_EFFECTOR_POSITION_X = "Effector Position X"
SOCKET_EFFECTOR_POSITION_Y = "Effector Position Y"
SOCKET_EFFECTOR_POSITION_Z = "Effector Position Z"
SOCKET_EFFECTOR_USE_ROTATION = "Effector Use Rotation"
SOCKET_EFFECTOR_ROTATION_X = "Effector Rotation X"
SOCKET_EFFECTOR_ROTATION_Y = "Effector Rotation Y"
SOCKET_EFFECTOR_ROTATION_Z = "Effector Rotation Z"
SOCKET_EFFECTOR_USE_SCALE = "Effector Use Scale"
SOCKET_EFFECTOR_SCALE_X = "Effector Scale X"
SOCKET_EFFECTOR_SCALE_Y = "Effector Scale Y"
SOCKET_EFFECTOR_SCALE_Z = "Effector Scale Z"
SOCKET_EFFECTOR_2_OBJECT = "Plain Effector 2"
SOCKET_EFFECTOR_2_TYPE = "Effector 2 Type"
SOCKET_EFFECTOR_2_FIELD = "Effector 2 Field"
SOCKET_EFFECTOR_2_SEED = "Effector 2 Seed"
SOCKET_EFFECTOR_2_ENABLED = "Effector 2 Enabled"
SOCKET_EFFECTOR_2_INVERT = "Effector 2 Inverse"
SOCKET_EFFECTOR_2_STRENGTH = "Effector 2 Strength"
SOCKET_EFFECTOR_2_RADIUS = "Effector 2 Radius"
SOCKET_EFFECTOR_2_HEIGHT = "Effector 2 Height"
SOCKET_EFFECTOR_2_LENGTH = "Effector 2 Length"
SOCKET_EFFECTOR_2_FALLOFF = "Effector 2 Falloff"
SOCKET_EFFECTOR_2_USE_POSITION = "Effector 2 Use Position"
SOCKET_EFFECTOR_2_POSITION_X = "Effector 2 Position X"
SOCKET_EFFECTOR_2_POSITION_Y = "Effector 2 Position Y"
SOCKET_EFFECTOR_2_POSITION_Z = "Effector 2 Position Z"
SOCKET_EFFECTOR_2_USE_ROTATION = "Effector 2 Use Rotation"
SOCKET_EFFECTOR_2_ROTATION_X = "Effector 2 Rotation X"
SOCKET_EFFECTOR_2_ROTATION_Y = "Effector 2 Rotation Y"
SOCKET_EFFECTOR_2_ROTATION_Z = "Effector 2 Rotation Z"
SOCKET_EFFECTOR_2_USE_SCALE = "Effector 2 Use Scale"
SOCKET_EFFECTOR_2_SCALE_X = "Effector 2 Scale X"
SOCKET_EFFECTOR_2_SCALE_Y = "Effector 2 Scale Y"
SOCKET_EFFECTOR_2_SCALE_Z = "Effector 2 Scale Z"
SOCKET_EFFECTOR_3_OBJECT = "Plain Effector 3"
SOCKET_EFFECTOR_3_TYPE = "Effector 3 Type"
SOCKET_EFFECTOR_3_FIELD = "Effector 3 Field"
SOCKET_EFFECTOR_3_SEED = "Effector 3 Seed"
SOCKET_EFFECTOR_3_ENABLED = "Effector 3 Enabled"
SOCKET_EFFECTOR_3_INVERT = "Effector 3 Inverse"
SOCKET_EFFECTOR_3_STRENGTH = "Effector 3 Strength"
SOCKET_EFFECTOR_3_RADIUS = "Effector 3 Radius"
SOCKET_EFFECTOR_3_HEIGHT = "Effector 3 Height"
SOCKET_EFFECTOR_3_LENGTH = "Effector 3 Length"
SOCKET_EFFECTOR_3_FALLOFF = "Effector 3 Falloff"
SOCKET_EFFECTOR_3_USE_POSITION = "Effector 3 Use Position"
SOCKET_EFFECTOR_3_POSITION_X = "Effector 3 Position X"
SOCKET_EFFECTOR_3_POSITION_Y = "Effector 3 Position Y"
SOCKET_EFFECTOR_3_POSITION_Z = "Effector 3 Position Z"
SOCKET_EFFECTOR_3_USE_ROTATION = "Effector 3 Use Rotation"
SOCKET_EFFECTOR_3_ROTATION_X = "Effector 3 Rotation X"
SOCKET_EFFECTOR_3_ROTATION_Y = "Effector 3 Rotation Y"
SOCKET_EFFECTOR_3_ROTATION_Z = "Effector 3 Rotation Z"
SOCKET_EFFECTOR_3_USE_SCALE = "Effector 3 Use Scale"
SOCKET_EFFECTOR_3_SCALE_X = "Effector 3 Scale X"
SOCKET_EFFECTOR_3_SCALE_Y = "Effector 3 Scale Y"
SOCKET_EFFECTOR_3_SCALE_Z = "Effector 3 Scale Z"
SOCKET_DISTRIBUTION_MODE = "Mode (0 Grid, 1 Linear, 2 Radial, 3 Object)"
SOCKET_SPACING_MODE = "Spacing Mode (0 Per Step, 1 Endpoint)"
SOCKET_COUNT_X = "Count X"
SOCKET_COUNT_Y = "Count Y"
SOCKET_COUNT_Z = "Count Z"
SOCKET_SPACING_X = "Spacing X"
SOCKET_SPACING_Y = "Spacing Y"
SOCKET_SPACING_Z = "Spacing Z"
SOCKET_LINEAR_COUNT = "Linear Count"
SOCKET_LINEAR_SPACING = "Linear Spacing"
SOCKET_LINEAR_DIRECTION_X = "Direction X"
SOCKET_LINEAR_DIRECTION_Y = "Direction Y"
SOCKET_LINEAR_DIRECTION_Z = "Direction Z"
SOCKET_RADIAL_COUNT = "Radial Count"
SOCKET_RADIAL_RADIUS = "Radius"
SOCKET_RADIAL_ARC = "Arc"
SOCKET_RADIAL_AXIS = "Axis (0 Z, 1 X, 2 Y)"
SOCKET_RADIAL_ALIGN = "Align"
SOCKET_OBJECT_DISTRIBUTION_OBJECT = "Distribution Object"
SOCKET_OBJECT_DISTRIBUTION_MODE = "Object Mode (0 Vertices, 1 Polygons, 2 Spline)"
SOCKET_OBJECT_SPLINE_DISTRIBUTION = "Spline Distribution (0 Evaluated, 1 Count, 2 Step, 3 Even)"
SOCKET_OBJECT_SPLINE_COUNT = "Spline Count"
SOCKET_OBJECT_SPLINE_STEP = "Spline Step"
SOCKET_OBJECT_SPLINE_PER_SPLINE = "Spline Per Spline"
SOCKET_OBJECT_SPLINE_SMOOTH_ROTATION = "Spline Smooth Rotation"
SOCKET_OBJECT_ALIGNMENT = "Alignment (0 None, 1 Normals, 2 Center, 3 Tangent)"
SOCKET_OBJECT_UP_VECTOR = "Up Vector (0 Automatic, 1 X, 2 Y, 3 Z)"
SOCKET_SOURCE_POSITION_X = "Source Position X"
SOCKET_SOURCE_POSITION_Y = "Source Position Y"
SOCKET_SOURCE_POSITION_Z = "Source Position Z"
SOCKET_SOURCE_ROTATION_X = "Source Rotation X"
SOCKET_SOURCE_ROTATION_Y = "Source Rotation Y"
SOCKET_SOURCE_ROTATION_Z = "Source Rotation Z"
SOCKET_SOURCE_SCALE_X = "Source Scale X"
SOCKET_SOURCE_SCALE_Y = "Source Scale Y"
SOCKET_SOURCE_SCALE_Z = "Source Scale Z"

GRID_INPUT_DEFAULTS = {
    SOCKET_SOURCE_COUNT: 1,
    SOCKET_EFFECTOR_TYPE: 0,
    SOCKET_EFFECTOR_FIELD: 0,
    SOCKET_EFFECTOR_SEED: 1,
    SOCKET_EFFECTOR_ENABLED: False,
    SOCKET_EFFECTOR_INVERT: False,
    SOCKET_EFFECTOR_STRENGTH: 1.0,
    SOCKET_EFFECTOR_RADIUS: 3.0,
    SOCKET_EFFECTOR_HEIGHT: 6.0,
    SOCKET_EFFECTOR_LENGTH: 6.0,
    SOCKET_EFFECTOR_FALLOFF: 50,
    SOCKET_EFFECTOR_USE_POSITION: True,
    SOCKET_EFFECTOR_POSITION_X: 0.0,
    SOCKET_EFFECTOR_POSITION_Y: 0.0,
    SOCKET_EFFECTOR_POSITION_Z: 1.0,
    SOCKET_EFFECTOR_USE_ROTATION: False,
    SOCKET_EFFECTOR_ROTATION_X: 0.0,
    SOCKET_EFFECTOR_ROTATION_Y: 0.0,
    SOCKET_EFFECTOR_ROTATION_Z: 0.0,
    SOCKET_EFFECTOR_USE_SCALE: False,
    SOCKET_EFFECTOR_SCALE_X: 1.0,
    SOCKET_EFFECTOR_SCALE_Y: 1.0,
    SOCKET_EFFECTOR_SCALE_Z: 1.0,
    SOCKET_EFFECTOR_2_TYPE: 0,
    SOCKET_EFFECTOR_2_FIELD: 0,
    SOCKET_EFFECTOR_2_SEED: 2,
    SOCKET_EFFECTOR_2_ENABLED: False,
    SOCKET_EFFECTOR_2_INVERT: False,
    SOCKET_EFFECTOR_2_STRENGTH: 1.0,
    SOCKET_EFFECTOR_2_RADIUS: 3.0,
    SOCKET_EFFECTOR_2_HEIGHT: 6.0,
    SOCKET_EFFECTOR_2_LENGTH: 6.0,
    SOCKET_EFFECTOR_2_FALLOFF: 50,
    SOCKET_EFFECTOR_2_USE_POSITION: True,
    SOCKET_EFFECTOR_2_POSITION_X: 0.0,
    SOCKET_EFFECTOR_2_POSITION_Y: 0.0,
    SOCKET_EFFECTOR_2_POSITION_Z: 1.0,
    SOCKET_EFFECTOR_2_USE_ROTATION: False,
    SOCKET_EFFECTOR_2_ROTATION_X: 0.0,
    SOCKET_EFFECTOR_2_ROTATION_Y: 0.0,
    SOCKET_EFFECTOR_2_ROTATION_Z: 0.0,
    SOCKET_EFFECTOR_2_USE_SCALE: False,
    SOCKET_EFFECTOR_2_SCALE_X: 1.0,
    SOCKET_EFFECTOR_2_SCALE_Y: 1.0,
    SOCKET_EFFECTOR_2_SCALE_Z: 1.0,
    SOCKET_EFFECTOR_3_TYPE: 0,
    SOCKET_EFFECTOR_3_FIELD: 0,
    SOCKET_EFFECTOR_3_SEED: 3,
    SOCKET_EFFECTOR_3_ENABLED: False,
    SOCKET_EFFECTOR_3_INVERT: False,
    SOCKET_EFFECTOR_3_STRENGTH: 1.0,
    SOCKET_EFFECTOR_3_RADIUS: 3.0,
    SOCKET_EFFECTOR_3_HEIGHT: 6.0,
    SOCKET_EFFECTOR_3_LENGTH: 6.0,
    SOCKET_EFFECTOR_3_FALLOFF: 50,
    SOCKET_EFFECTOR_3_USE_POSITION: True,
    SOCKET_EFFECTOR_3_POSITION_X: 0.0,
    SOCKET_EFFECTOR_3_POSITION_Y: 0.0,
    SOCKET_EFFECTOR_3_POSITION_Z: 1.0,
    SOCKET_EFFECTOR_3_USE_ROTATION: False,
    SOCKET_EFFECTOR_3_ROTATION_X: 0.0,
    SOCKET_EFFECTOR_3_ROTATION_Y: 0.0,
    SOCKET_EFFECTOR_3_ROTATION_Z: 0.0,
    SOCKET_EFFECTOR_3_USE_SCALE: False,
    SOCKET_EFFECTOR_3_SCALE_X: 1.0,
    SOCKET_EFFECTOR_3_SCALE_Y: 1.0,
    SOCKET_EFFECTOR_3_SCALE_Z: 1.0,
    SOCKET_DISTRIBUTION_MODE: 0,
    SOCKET_SPACING_MODE: 0,
    SOCKET_COUNT_X: 3,
    SOCKET_COUNT_Y: 3,
    SOCKET_COUNT_Z: 1,
    SOCKET_SPACING_X: 2.0,
    SOCKET_SPACING_Y: 2.0,
    SOCKET_SPACING_Z: 2.0,
    SOCKET_LINEAR_COUNT: 3,
    SOCKET_LINEAR_SPACING: 2.0,
    SOCKET_LINEAR_DIRECTION_X: 1.0,
    SOCKET_LINEAR_DIRECTION_Y: 0.0,
    SOCKET_LINEAR_DIRECTION_Z: 0.0,
    SOCKET_RADIAL_COUNT: 8,
    SOCKET_RADIAL_RADIUS: 2.0,
    SOCKET_RADIAL_ARC: 6.283185307179586,
    SOCKET_RADIAL_AXIS: 0,
    SOCKET_RADIAL_ALIGN: True,
    SOCKET_OBJECT_DISTRIBUTION_MODE: 0,
    SOCKET_OBJECT_SPLINE_DISTRIBUTION: 3,
    SOCKET_OBJECT_SPLINE_COUNT: 12,
    SOCKET_OBJECT_SPLINE_STEP: 1.0,
    SOCKET_OBJECT_SPLINE_PER_SPLINE: True,
    SOCKET_OBJECT_SPLINE_SMOOTH_ROTATION: True,
    SOCKET_OBJECT_ALIGNMENT: 1,
    SOCKET_OBJECT_UP_VECTOR: 0,
    SOCKET_SOURCE_POSITION_X: 0.0,
    SOCKET_SOURCE_POSITION_Y: 0.0,
    SOCKET_SOURCE_POSITION_Z: 0.0,
    SOCKET_SOURCE_ROTATION_X: 0.0,
    SOCKET_SOURCE_ROTATION_Y: 0.0,
    SOCKET_SOURCE_ROTATION_Z: 0.0,
    SOCKET_SOURCE_SCALE_X: 1.0,
    SOCKET_SOURCE_SCALE_Y: 1.0,
    SOCKET_SOURCE_SCALE_Z: 1.0,
}

EFFECTOR_SOCKET_SETS = (
    {
        "object": SOCKET_EFFECTOR_OBJECT,
        "type": SOCKET_EFFECTOR_TYPE,
        "field": SOCKET_EFFECTOR_FIELD,
        "seed": SOCKET_EFFECTOR_SEED,
        "enabled": SOCKET_EFFECTOR_ENABLED,
        "invert": SOCKET_EFFECTOR_INVERT,
        "strength": SOCKET_EFFECTOR_STRENGTH,
        "radius": SOCKET_EFFECTOR_RADIUS,
        "height": SOCKET_EFFECTOR_HEIGHT,
        "length": SOCKET_EFFECTOR_LENGTH,
        "falloff": SOCKET_EFFECTOR_FALLOFF,
        "use_position": SOCKET_EFFECTOR_USE_POSITION,
        "position_x": SOCKET_EFFECTOR_POSITION_X,
        "position_y": SOCKET_EFFECTOR_POSITION_Y,
        "position_z": SOCKET_EFFECTOR_POSITION_Z,
        "use_rotation": SOCKET_EFFECTOR_USE_ROTATION,
        "rotation_x": SOCKET_EFFECTOR_ROTATION_X,
        "rotation_y": SOCKET_EFFECTOR_ROTATION_Y,
        "rotation_z": SOCKET_EFFECTOR_ROTATION_Z,
        "use_scale": SOCKET_EFFECTOR_USE_SCALE,
        "scale_x": SOCKET_EFFECTOR_SCALE_X,
        "scale_y": SOCKET_EFFECTOR_SCALE_Y,
        "scale_z": SOCKET_EFFECTOR_SCALE_Z,
    },
    {
        "object": SOCKET_EFFECTOR_2_OBJECT,
        "type": SOCKET_EFFECTOR_2_TYPE,
        "field": SOCKET_EFFECTOR_2_FIELD,
        "seed": SOCKET_EFFECTOR_2_SEED,
        "enabled": SOCKET_EFFECTOR_2_ENABLED,
        "invert": SOCKET_EFFECTOR_2_INVERT,
        "strength": SOCKET_EFFECTOR_2_STRENGTH,
        "radius": SOCKET_EFFECTOR_2_RADIUS,
        "height": SOCKET_EFFECTOR_2_HEIGHT,
        "length": SOCKET_EFFECTOR_2_LENGTH,
        "falloff": SOCKET_EFFECTOR_2_FALLOFF,
        "use_position": SOCKET_EFFECTOR_2_USE_POSITION,
        "position_x": SOCKET_EFFECTOR_2_POSITION_X,
        "position_y": SOCKET_EFFECTOR_2_POSITION_Y,
        "position_z": SOCKET_EFFECTOR_2_POSITION_Z,
        "use_rotation": SOCKET_EFFECTOR_2_USE_ROTATION,
        "rotation_x": SOCKET_EFFECTOR_2_ROTATION_X,
        "rotation_y": SOCKET_EFFECTOR_2_ROTATION_Y,
        "rotation_z": SOCKET_EFFECTOR_2_ROTATION_Z,
        "use_scale": SOCKET_EFFECTOR_2_USE_SCALE,
        "scale_x": SOCKET_EFFECTOR_2_SCALE_X,
        "scale_y": SOCKET_EFFECTOR_2_SCALE_Y,
        "scale_z": SOCKET_EFFECTOR_2_SCALE_Z,
    },
    {
        "object": SOCKET_EFFECTOR_3_OBJECT,
        "type": SOCKET_EFFECTOR_3_TYPE,
        "field": SOCKET_EFFECTOR_3_FIELD,
        "seed": SOCKET_EFFECTOR_3_SEED,
        "enabled": SOCKET_EFFECTOR_3_ENABLED,
        "invert": SOCKET_EFFECTOR_3_INVERT,
        "strength": SOCKET_EFFECTOR_3_STRENGTH,
        "radius": SOCKET_EFFECTOR_3_RADIUS,
        "height": SOCKET_EFFECTOR_3_HEIGHT,
        "length": SOCKET_EFFECTOR_3_LENGTH,
        "falloff": SOCKET_EFFECTOR_3_FALLOFF,
        "use_position": SOCKET_EFFECTOR_3_USE_POSITION,
        "position_x": SOCKET_EFFECTOR_3_POSITION_X,
        "position_y": SOCKET_EFFECTOR_3_POSITION_Y,
        "position_z": SOCKET_EFFECTOR_3_POSITION_Z,
        "use_rotation": SOCKET_EFFECTOR_3_USE_ROTATION,
        "rotation_x": SOCKET_EFFECTOR_3_ROTATION_X,
        "rotation_y": SOCKET_EFFECTOR_3_ROTATION_Y,
        "rotation_z": SOCKET_EFFECTOR_3_ROTATION_Z,
        "use_scale": SOCKET_EFFECTOR_3_USE_SCALE,
        "scale_x": SOCKET_EFFECTOR_3_SCALE_X,
        "scale_y": SOCKET_EFFECTOR_3_SCALE_Y,
        "scale_z": SOCKET_EFFECTOR_3_SCALE_Z,
    },
)

EFFECTOR_OBJECT_SOCKET_NAMES = tuple(
    socket_set["object"] for socket_set in EFFECTOR_SOCKET_SETS
)
EFFECTOR_VALUE_SOCKET_NAMES = tuple(
    socket_name
    for socket_set in EFFECTOR_SOCKET_SETS
    for key, socket_name in socket_set.items()
    if key != "object"
)
